### PR TITLE
meditation screen overflow fix

### LINKED ISSUE #147: [Bug]Screen overflow in landscape in meditation screen
**Describe the bug**
Screen overflow at bottom in the meditation screen

**To Reproduce**
1. Go to 'Meditation Screen'
2. Switch to landscape mode
3. See error

**Expected behavior**
Screen should be scrollable if overflowing

**Screenshots**
Screenshot_1736066566
Simulator Screenshot - iPhone 16 Plus - 2025-01-05 at 14 13 09

### PR DESCRIPTION
**Pull request by Sanat-Jha**
### Related Issue  
Closes #147 

### Type of Change
Put `x` inside the square bracket to specify what type of change your PR is:  
- [x] Bug Fix  

### Description of Change  
Fixed the over flow issue in meditation screen landscape view.

### CODE REVIEW

File: lib/screens/meditation_screen.dart [hunk 1]
```diff
@@ -149,224 +146,239 @@ class _MeditationScreenState extends State<MeditationScreen>
...
-                            'Mindful Moments with Taskly',
-                            style: TextStyle(
-                              fontSize: 20,
-                              color: Colors.white70,
-                              letterSpacing: 1.5,
-                            ),
+                  // Main content
+                  CustomScrollView(
+                    slivers: [
+                      SliverAppBar(
```
Comment (pranavkonidena) [inline lib/screens/meditation_screen.dart:176]: Nice solution!

**Review by pranavkonidena — APPROVED** [review]
LGTM! Ready for merge
