### PR TITLE
Collapsible tip of the day box #100

### LINKED ISSUE #100: [Bug]Tip of the day should be collapsable
**Describe the bug**
The "Tip of the day section" is always visible on the screen which user may not want to see. 

**Expected behavior**
Tip of the day should be visible on app start and then user should have an option to close the tip box or again open it.

### PR DESCRIPTION
**Pull request by Sanat-Jha**
### Related Issue  
Closes #100 

### Type of Change
Put `x` inside the square bracket to specify what type of change your PR is:  
- [x] Bug Fix   

### Description of Change  
In the menu on top right corner, now there is an option to close or open the tip of the day box.

### Demo  

https://github.com/user-attachments/assets/b8f47792-034f-4243-895a-0a3413107dc9

### CODE REVIEW

File: lib/enums/taskoptions.dart [hunk 1]
```diff
@@ -1,2 +1,2 @@
 // Enum to represent options in the menu
-enum TaskOption { deleteAll }
\ No newline at end of file
+enum TaskOption { deleteAll,toggleTipVisibility }
```
Comment (pranavkonidena) [inline lib/enums/taskoptions.dart:2]: Please add EOF

**Review by pranavkonidena — CHANGES_REQUESTED** [review]

File: lib/enums/taskoptions.dart (hunk 1 above)
Comment (Sanat-Jha) [reply lib/enums/taskoptions.dart]: Done, please review

**Review by pranavkonidena — APPROVED** [review]
Please resolve merge conflicts @Sanat-Jha. Will merge post resolution. Changes LGTM

**Comment by Sanat-Jha** [comment]
@pranavkonidena merge conflicts resolved.
